backend:
  name: github
  repo: Rosemary-Hogarth/Julius-Heinemann-Art
  branch: master



media_library:
  name: cloudinary
  config:
    cloud_name: dyciaxri0
    api_key: 923446252637638


collections:
  - name: "exhibitions"
    label: "Exhibitions"
    folder: "exhibitions"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order", "year", "title"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the exhibitions as you want them displayed." }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Venue and Place and Date", name: "locationDate", widget: "string", required: false}
      - {label: "Type of show and curated by and other artists", name: "type", widget: "string", required: false}
      # - {label: "Category", name: "category", widget: "select", options: ["Solo show", "Group show", "Installation", "Duo show"], required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/exhibitions/{{ title | slugify }}/"}
      - label: "Gallery Images"
        name: "images"
        widget: "list"
        field:
          {label: "Image", name: "image", widget: "image"}
      - {label: "Exhibition Text Title", name: "exhibitionTextTitle", widget: "string"}
      - {label: "Exhibition Text Type and Venue and Place", name: "exhibitionTextLocation", widget: "string"}
      - {label: "Exhibition Text Curated By", name: "exhibitionTextCurated", widget: "string", required: false}
      - {label: "Exhibition Text Other Artists", name: "exhibitionTextArtists", widget: "string", required: false}
      - {label: "Exhibition Text Dates", name: "exhibitionTextDates", widget: "string"}
      - {label: "Exhibition Text English", name: "exhibitionTextEn", widget: "markdown", required: false}
      - {label: "Exhibition Text German", name: "exhibitionTextDe", widget: "markdown", required: false}
      - {label: "Exhibition Text Spanish", name: "exhibitionTextEs", widget: "markdown", required: false}
      - {label: "Exhibition Text Portuguese", name: "exhibitionTextPt", widget: "markdown", required: false}
      - {label: "Exhibition Text French", name: "exhibitionTextFr", widget: "markdown", required: false}
      - {label: "Exhibition Text Chinese", name: "exhibitionTextCh", widget: "markdown", required: false}
      - {label: "Exhibition Text Korean", name: "exhibitionTextKo", widget: "markdown", required: false}



# New "Works" Collection
  - name: "works"
    label: "Works"
    folder: "works"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order", "year", "name"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the works as you want them displayed." }
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Extra Info", name: "extra", widget: "string", required: false}
      - {label: "Extra Info Photographer", name: "extraPhoto", widget: "string", required: false}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Installation", "Painting", "Watercolour", "Collage", "Drawing", "Book", "Object"], required: false} # Filter category
      - {label: "Type", name: "type", widget: "select", options: ["Single", "Installation", "Book"], default: "Single"}
      - {label: "Mobile Work Title", name: "workMobileName", widget: "string", required: false}
      - {label: "Mobile Work Year", name: "workMobileYear", widget: "string", required: false}
      - {label: "Mobile Work Size", name: "workMobileSize", widget: "string", required: false}
      - {label: "Mobile Work Material", name: "workMobileMaterial", widget: "string", required: false}
      - { label: "Image", name: "image", widget: "image", required: false }
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/works/{{ name | slugify }}/"}
      - label: "Installation Images"
        name: "installationImages"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
        required: false
      - label: "Book Images"
        name: "bookImages"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
        required: false


  # - name: "works"
  #   label: "Works"
  #   files:
  #     - name: "works"
  #       label: "Works"
  #       file: "works/works.yml"  # This stores all artworks in a single YAML file
  #       fields:
  #         - label: "Works"
  #           name: "works"
  #           widget: "list"
  #           label_singular: "Work"
  #           summary: "{{name}} ({{year}})"
  #           fields:
  #             - { label: "Name", name: "name", widget: "string" }
  #             - { label: "Year", name: "year", widget: "number" }
  #             - { label: "Extra Info", name: "extra", widget: "string", required: false }
  #             - { label: "Extra Info Photographer", name: "extraPhoto", widget: "string", required: false }
  #             - { label: "Dimensions", name: "dimensions", widget: "string" }
  #             - { label: "Medium", name: "medium", widget: "string" }
  #             - { label: "Category", name: "category", widget: "select", options: ["Installation", "Painting", "Watercolour", "Collage", "Drawing", "Object"] }
  #             - { label: "Type", name: "type", widget: "select", options: ["Single", "Installation"], default: "Single" }
  #             - { label: "Image", name: "image", widget: "image", required: false }
  #             - { label: "Permalink", name: "permalink", widget: "hidden", default: "/works/{{ name | slugify }}/" }
  #             - label: "Gallery Images"
  #               name: "images"
  #               widget: "list"
  #               fields:
  #                 - { label: "Image", name: "image", widget: "image" }



  - name: "homepage_slideshow"
    label: "Homepage Slideshow"
    folder: "homepage_slideshow"
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Order", name: "order", widget: "number", default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}



  - name: "publications"
    label: "Publications"
    folder: "publications"
    create: true
    slug: '{{publicationTitle | slugify}}'
    fields:
      - {label: "Publication Title", name: "publicationTitle", widget: "string", required: true}
      - {label: "Catalogue ID", name: "catalogueId", widget: "string", required: true, hint: "This keeps the slideshows separate"}
      - {label: "Main Image", name: "mainImage", widget: "image", required: true}
      - label: "Gallery Images"
        name: "galleryImages"
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: true}
          - {label: "Catalogue Name", name: "catalogueName", widget: "string", required: false}
          - {label: "Catalogue Info", name: "catalogueInfo", widget: "string", required: false}
      - {label: "Publication Text Author", name: "publicationTextAuthor", widget: "string", required: false}
      - {label: "Publication Details", name: "publicationDetails", widget: "text", required: false}
      - {label: "Designed by", name: "designedBy", widget: "string", required: false}
      - {label: "Published by", name: "publishedBy", widget: "string", required: false}
      - {label: "ISBN", name: "isbn", widget: "string", required: false}
      - {label: "Publication Price", name: "publicationPrice", widget: "string", required: false}




  - name: "about"
    label: "About"
    folder: "about"
    create: true
    slug: '{{title | slugify}}'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Quote Line 1", name: "quote1", widget: "string", required: true}
      - {label: "Quote Line 2", name: "quote2", widget: "string", required: true}
      - {label: "Quote Line 3", name: "quote3", widget: "string", required: true}
      - {label: "Quote Line 4", name: "quote4", widget: "string", required: true}
      - {label: "Quote German Line 1", name: "quoteDe1", widget: "string", required: true}
      - {label: "Quote German Line 2", name: "quoteDe2", widget: "string", required: true}
      - {label: "Quote German Line 3", name: "quoteDe3", widget: "string", required: true}
      - {label: "Quote German Line 4", name: "quoteDe4", widget: "string", required: true}
      - {label: "Quote Author", name: "quoteAuthor", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/about/{{ title | slugify }}/"}
      - {label: "Practice English", name: "practiceEn", widget: "markdown", required: true}
      - {label: "Practice German", name: "practiceDe", widget: "markdown", required: false}

      - label: "CV Biography"
        name: "cv_bio"
        widget: "string"
        required: true


      # Education section with specific years and institutions
      - label: "Education"
        name: "cv_education"
        widget: "list"
        required: true
        fields:
          - { label: "Year", name: "year", widget: "string" }
          - { label: "Institution", name: "institution", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }

      # Grants / Residencies section
      - label: "Grants / Residencies"
        name: "cv_grants_residencies"
        widget: "list"
        required: false
        fields:
          - { label: "Year", name: "year", widget: "string" }
          - { label: "Grant/Residency", name: "grant_residency", widget: "string" }

      # Solo Exhibitions section
      - label: "Solo Exhibitions"
        name: "cv_solo_exhibitions"
        widget: "list"
        required: false
        fields:
          - { label: "Year", name: "year", widget: "string" }
          - { label: "Exhibition Title", name: "exhibitionTitle", widget: "string" }
          - { label: "Exhibition Details", name: "exhibitionDetails", widget: "string" }

      # Group Exhibitions section
      - label: "Group Exhibitions"
        name: "cv_group_exhibitions"
        widget: "list"
        required: false
        fields:
          - { label: "Year", name: "year", widget: "string" }
          - { label: "Exhibition Title", name: "exhibitionTitle", widget: "string" }
          - { label: "Exhibition Details", name: "exhibitionDetails", widget: "string" }

      # Bibliography section
      - label: "Bibliography"
        name: "cv_bibliography"
        widget: "list"
        required: false
        fields:
          - { label: "Year", name: "year", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publisher", name: "publisher", widget: "string" }

      - label: "Texts"
        name: "texts"
        widget: "relation"
        collection: "about-texts"
        search_fields: ["textTitle"]
        value_field: "{{slug}}"
        display_fields: ["textTitle"]
        multiple: true


      # - name: "about-texts"
      #   label: "About Texts"
      #   folder: "about/texts"
      #   create: true
      #   slug: "{{textTitle | slugify}}"
      #   fields:
      #     - {label: "Text Title English", name: "textTitleEn", widget: "string", required: true}
      #     - {label: "Text Title German", name: "textTitleDe", widget: "string", required: false}
      #     - {label: "Text Title Spanish", name: "textTitleEs", widget: "string", required: false}
      #     - {label: "Text Title Portuguese", name: "textTitlePt", widget: "string", required: false}
      #     - {label: "Text Title French", name: "textTitleFr", widget: "string", required: false}

      #     - {label: "Text Author English", name: "textAuthorEn", widget: "string", required: true}
      #     - {label: "Text Author German", name: "textAuthorDe", widget: "string", required: false}
      #     - {label: "Text Author Spanish", name: "textAuthorEs", widget: "string", required: false}
      #     - {label: "Text Author Portuguese", name: "textAuthorPt", widget: "string", required: false}
      #     - {label: "Text Author French", name: "textAuthorFr", widget: "string", required: false}

      #     - {label: "Text Details English", name: "textDetailsEn", widget: "string", required: true}
      #     - {label: "Text Details German", name: "textDetailsDe", widget: "string", required: false}
      #     - {label: "Text Details Spanish", name: "textDetailsEs", widget: "string", required: false}
      #     - {label: "Text Details Portuguese", name: "textDetailsPt", widget: "string", required: false}
      #     - {label: "Text Details French", name: "textDetailsFr", widget: "string", required: false}

      #     - {label: "Full Text English", name: "fullTextEn", widget: "markdown", required: true}
      #     - {label: "Full Text German", name: "fullTextDe", widget: "markdown", required: false}
      #     - {label: "Full Text Spanish", name: "fullTextEs", widget: "markdown", required: false}
      #     - {label: "Full Text Portuguese", name: "fullTextPt", widget: "markdown", required: false}
      #     - {label: "Full Text French", name: "fullTextFr", widget: "markdown", required: false}


  - name: "about-texts"
    label: "About Texts"
    folder: "about/texts"
    create: true
    slug: "{{textTitle | slugify}}"
    fields:
      - {label: "Text Title", name: "textTitle", widget: "string", required: true}
      - {label: "Text Author", name: "textAuthor", widget: "string", required: true}
      - {label: "Text Details", name: "textDetails", widget: "string", required: true}
      - {label: "Full Text English", name: "fullTextEn", widget: "markdown", required: true}
      - {label: "Full text German", name: "fullTextDe", widget: "markdown", required: false}
      - {label: "Full Text Spanish", name: "fullTextEs", widget: "markdown", required: false}
      - {label: "Full Text Portuguese", name: "fullTextPt", widget: "markdown", required: false}
      - {label: "Full Text French", name: "fullTextFr", widget: "markdown", required: false}



  - name: "studio"
    label: "Contact studio"
    folder: "contact/studio"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the studios as you want them displayed." }
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Studio Name", name: "studioName", widget: "string", required: true}
      - {label: "Studio Address", name: "studioAddress", widget: "text"}
      - {label: "Studio Email", name: "studioEmail", widget: "string"}


  - name: "gallery"
    label: "Contact gallery"
    folder: "contact/gallery"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the galleries as you want them displayed." }
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Gallery Name", name: "galleryName", widget: "string", required: true}
      - {label: "Gallery Address", name: "galleryAddress", widget: "text"}
      - {label: "Gallery Website", name: "galleryWebsite", widget: "string"}




  - name: "imprint"
    label: "Imprint"
    folder: "imprint"
    create: true
    slug: '{{title | slugify}}'
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Text", name: "text", widget: "markdown", required: true }


  - name: "privacy"
    label: "Privacy"
    folder: "privacy"
    create: true
    slug: '{{title | slugify}}'
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Text", name: "text", widget: "markdown", required: true }




  - name: "upcoming"
    label: "Upcoming Exhibitions"
    folder: "news/upcoming"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order", "title"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the news items as you want them displayed." }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Location", name: "location", widget: "string", required: true }
      - { label: "Opening", name: "opening", widget: "string" }
      - { label: "Web", name: "web", widget: "string", required: true }

  - name: "recent"
    label: "Recent Exhibitions"
    folder: "news/recent"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order", "title"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the news items as you want them displayed." }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Location", name: "location", widget: "string", required: true }
      - { label: "Opening", name: "opening", widget: "string", required: false }
      - { label: "Web", name: "web", widget: "string", required: true }

  - name: "press"
    label: "Press"
    folder: "news/press"
    create: true
    slug: '{{title | slugify}}'
    sortableFields: ["order", "title"]
    fields:
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Order the news items as you want them displayed." }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Magazine", name: "magazine", widget: "string", required: true }
      - { label: "link", name: "link", widget: "string", required: true}
